### ISSUE TITLE
Run manageiq-providers-openstack-test-$(public-clouds) in periodic-2 pipeline

### ISSUE THREAD

**Issue by kiwik** [theopenlab/openlab#152]
Let's make things better!

### Describe the bug
We trigger manageiq jobs in `check-generic-cloud` pipeline manually, actually those jobs don't create any resource for public cloud environment, so we can put them into periodic pipeline to be triggered automatically, now we have `periodic-2` pipeline run at UTC-0 22:00, that is a good time to avoid tenant quota limit of public cloud account to run jobs, so plan to move all of manageiq jobs into it, and we can switch to official project [manageiq/manageiq-providers-openstack](https://github.com/manageiq/manageiq-providers-openstack) in OpenLab configuration

```yaml
    check-generic-cloud:
      jobs:
        - manageiq-providers-openstack-test-huaweicloud
        - manageiq-providers-openstack-test-opentelekomcloud
        - manageiq-providers-openstack-test-orange
```

### Related Job information
If the bug is related a CI job, put the job information below:
- manageiq-providers-openstack-test-devstack-master
- manageiq-providers-openstack-test-devstack-mitaka
- manageiq-providers-openstack-test-devstack-newton
- manageiq-providers-openstack-test-devstack-ocata
- manageiq-providers-openstack-test-devstack-pike
- manageiq-providers-openstack-test-devstack-queens
- manageiq-providers-openstack-test-devstack-rocky
- manageiq-providers-openstack-test-huaweicloud
- manageiq-providers-openstack-test-opentelekomcloud
- manageiq-providers-openstack-test-orange

### Steps to reproduce the issue
Describe how to reproduce the issue:
