### ISSUE TITLE
Support ARM pool

### ISSUE THREAD

**Issue by Yikun** [theopenlab/openlab#194]
If you are interested in testing and improving support for the cloud-related SDKs/Tools as well as platforms in OpenLab, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [x] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [x] Application Ecosystem
- [ ] Other

### If this is for an open source project what is it?
Yes

### Brief project description
This project try to build the ARM pool in Openlab.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
unrelated

### What kind of machines (VMs or Baremetal) and how many do you expect to use?
ARM

### What OS are you planning to use?
- Ubuntu 16.04 aarch64

### Any special network configuration you expect or anticipate implementing?
unrelated

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
ARM cpu

### What testing are you planning to implement or need assistance implementing?
Build a test job and run this test job in a arm node

### How will this testing advance application and/or tooling built on-top of open infrastructure?
unrelated

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
unrelated

**Comment by Yikun** [comment]
- [Done] Created the ARM VM using nodepool.
1. We can create ARM vm from cloud image, the nodepool yaml is something like:
```yaml
labels:
  - name: ubuntu-xenial-vxh-arm64
    min-ready: 1

providers:
  - name: vexxhost-openlaballinone
    cloud: vexxhost
    driver: openstack
    image-name-format: 'openlab-{image_name}-{timestamp}'
    launch-timeout: 900
    boot-timeout: 600
    max-concurrency: 10
    cloud-images:
      - name: ubuntu-xenial-vxh-arm64
        # the username of this image
        username: ubuntu
        # this image-name is the uuid of arm image
        image-name: 'de8b384c-5298-48aa-8803-cdb3047ac3a1'
    pools:
      - name: ubuntu-xenial-allinone
        max-ram: 163840
        networks:
          - int-net
        labels:
          - name: ubuntu-xenial-vxh-arm64
            cloud-image: ubuntu-xenial-vxh-arm64
            flavor-name: 'v2-standard-1'
            # We can inject the keypair using key-name
            key-name: allinone-zuul-key
```

2. The current exists image doesn't include some required package like python, so we need build the custom ARM image.
- [Done] Created
