### ISSUE TITLE
Gophercloud: Add Train and Ussuri triggers

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab#574]
I'm currently fixing up some of the Gophercloud acceptance tests and wanted to add support to be able to do:

```
recheck stable/train
recheck stable/ussuri
```

I've added the appropriate job definitions to Gophercloud's local Zuul configuration, but is there something additional that needs added on OpenLab's side?

**Comment by bzhaoopenstack** [comment]
Hi @jtopjian 

```
- pipeline:
    name: cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15
    description: |
      Commenting "/test cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15" enter this
      pipeline to run the tests job of Kubernetes+OpenStack E2E conformance test scenarios and receive an initial
      +/-1 Verified vote.
    manager: independent
    trigger:
      github:
        - event: pull_request
          action:
            - opened
            - changed
            - reopened
        - event: pull_request
          action: comment
          comment: (?i)^\s*\/test cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1\.15\s*$
        - event: pull_request
          action: comment
          comment: (?i)^\s*\/retest\s*$
        - event: pull_request
          action: comment
          comment: (?i)^\s*\/test all\s*$
```
I think you need add a pipeline for the new comment triggers like above in https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/pipelines.yaml , looks the same with https://github.com/gophercloud/gophercloud/blob/master/.zuul.yaml#L92
