### ISSUE TITLE
[urgent] Zuul config can't be reloaded

### ISSUE THREAD

**Issue by EmilienM** [theopenlab/openlab#880]
See https://github.com/gophercloud/gophercloud/issues/2275 for details

**Comment by wangxiyuan** [comment]
@fffrog This need a zuul restart. Please !

**Comment by EmilienM** [comment]
@wangxiyuan I'm not sure a Zuul restart will be enough, it seems to be a configuration issue in Zuul. See the traceback:

https://status.openlabtesting.org/config-errors

```
    terraform-provider-openstack/terraform-provider-openstack - .zuul.yaml (stable-website)

    Zuul encountered a syntax error while parsing its configuration in the
    repo terraform-provider-openstack/terraform-provider-openstack on
    branch stable-website.  The error was:

      The project "terraform-providers/terraform-provider-openstack" was not
      found.  All projects referenced within a Zuul configuration must first
      be added to the main configuration file by the Zuul administrator.

    The error appears in the following project stanza:

      project:
          name: terraform-providers/terraform-provider-openstack
          check:
            jobs:
              - terraform-provider-openstack-unittest
              - terraform-provider-openstack-acceptance-test
          recheck-newton:
            jobs:
              - terraform-provider-openstack-acceptance-test-newton
          recheck-ocata:
            jobs:
              - terraform-provider-openstack-acceptance-test-ocata
          recheck-pike:
            jobs:
              - terraform-provider-openstack-acceptance-test-pike
          recheck-queens:
            jobs:
              - terraform-provider-openstack-acceptance-test-queens
          recheck-rocky:
            jobs:
              - terraform-provider-openstack-acceptance-test-rocky
          recheck-stein:
            jobs:
              - terraform-provider-openstack-acceptance-test-stein
          recheck-trove:
            jobs:
              - terraform-provider-openstack-acceptance-test-trove
          recheck-designate:
            jobs:
              - terraform-provider-openstack-acceptance-test-designate
          recheck-lbaas:
            jobs:
              - terraform-provider-openstack-acceptance-test-lbaas
          recheck-fwaas:
            jobs:
              - terraform-provider-openstack-acceptance-test-fwaas

      in "terraform-provider-openstack/terraform-provider-openstack/.zuul.yaml@stable-website", line 1, column 3
```
